### PR TITLE
version sort - hotfix style - closes #104

### LINKED ISSUE #104: Version sorting
http://www.jsdelivr.com/projects/react
>React lastversion shows 0.14.0-rc1 instead of 0.14.0
https://github.com/jsdelivr/jsdelivr/issues/7281

The site uses the API sorting. We should short the versions correctly in the API by default. 0.14.0 > 0.14.0-rc1 > 0.14.0-beta1

### PR DESCRIPTION
**Pull request by UnbounDev**

### CODE REVIEW

**Comment by UnbounDev** [comment]
@jimaek merge when ready!

**Comment by jimaek** [comment]
The build fails

**Comment by megawac** [comment]
This should be done with semverish. Also it should be implemented on api sync rather than here

**Comment by UnbounDev** [comment]
I agree on the latter, ultimately the sort ought to take place on api-sync, why semverish though? The semver module is used by npm and has clear community support.

**Comment by megawac** [comment]
Semverish is an extension of npm with full test compatability. its to
support versioning schemes besides semver without erroring (like semver
will when you try to parse things like SoundManager2 versions)

**Comment by megawac** [comment]
https://github.com/megawac/SemVish

**Comment by megawac** [comment]
Anyway @UnbounDev this file on `api-sync` should be removed and replaced with `semvish` and https://github.com/jsdelivr/api-sync/blob/master/lib/sort_versions.js updated

**Pull request merged**
