### PR TITLE
Revert "version sort - hotfix style - closes #104"

### LINKED ISSUE #104: Version sorting
http://www.jsdelivr.com/projects/react
>React lastversion shows 0.14.0-rc1 instead of 0.14.0
https://github.com/jsdelivr/jsdelivr/issues/7281

The site uses the API sorting. We should short the versions correctly in the API by default. 0.14.0 > 0.14.0-rc1 > 0.14.0-beta1

### PR DESCRIPTION
**Pull request by jimaek**
Reverts jsdelivr/api#105

More info https://github.com/jsdelivr/api/issues/106

@megawac

### CODE REVIEW

**Comment by jimaek** [comment]
@megawac One test fails. Is it safe to merge?

**Comment by jimaek** [comment]
The wercker build fails as well, cant deploy

```
2015-10-14T12:52:26.096Z] Wed Oct 14 2015 12:52:26 GMT+0000 (UTC): Node server stopped.

TypeError: Cannot read property 'name' of undefined
at Request._callback (/pipeline/build/tasks/sync.js:126:23)
at Request.self.callback (/pipeline/build/node_modules/request/request.js:344:22)
at Request.emit (events.js:98:17)
at Request.<anonymous> (/pipeline/build/node_modules/request/request.js:1239:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/pipeline/build/node_modules/request/request.js:1187:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:448:13)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by megawac** [comment]
Odd, it works locally

**Comment by megawac** [comment]
It passes on travis re run
https://travis-ci.org/jsdelivr/api/builds/85320462

**Comment by jimaek** [comment]
yeah passed on a ru-run on wercker as well. Any idea why?

**Comment by megawac** [comment]
Nope, but it should now warn instead of crash

**Comment by jimaek** [comment]
Everything looks fine. Thank you

**Pull request merged**
