### PR TITLE
Drop unused fields

### LINKED ISSUE #74: Remove useless fields
```
"zip": "",
"mainfile2": "",
```
These can die in peace.

Also do we need `"$loki": 858` ?

### PR DESCRIPTION
**Pull request by megawac**
Fixes #74

### CODE REVIEW

**Comment by jimaek** [comment]
No related changes to api-sync?

**Comment by megawac** [comment]
I'll check later tonight

**Comment by UnbounDev** [comment]
There are no changes to api-sync for this issue, rather, the [schema](https://github.com/jsdelivr/api/blob/master/db/index.js) in use should change s.t. each CDN has it's own schema whose definition drops the unused fields. Note that changing the app at this layer will effect content served via the api/v1 endpoints.

**Comment by UnbounDev** [comment]
Ha! Sorry I read this thinking it was an issue - @megawac has it correct this is an appropriate fix.

**Pull request merged**
