### PR TITLE
Fuzzyish search support

### LINKED ISSUE #10: How to find same project, different CDN, different "name" field?
How can I find just the Ember CDN, if:
```
http://api.jsdelivr.com/v1/cdnjs/libraries?name=lodash*&fields=name
[{"name": "lodash.js"}]
http://api.jsdelivr.com/v1/jsdelivr/libraries?name=lodash*&fields=name
[{"name": "lodash"}]
http://api.jsdelivr.com/v1/cdnjs/libraries?name=ember*&fields=name
[{"name":"ember-data-django-rest-adapter"},{"name":"ember-data.js"},{"name":"ember-resource.js"},{"name":"ember.js"}]
http://api.jsdelivr.com/v1/jsdelivr/libraries?name=ember*&fields=name
[{"name":"ember.localstorage-adapter"},{"name":"ember.table"},{"name":"emberjs"}]
```
There are other mismatched project names: `underscore.js`|`underscorejs`, `can.js`|`canjs`, hard to say how many now or in future.  Not sure of the best approach?
* client-side or server-side lookup table (might grow large)
* switching to RegEx, since I can't figure out how to use [minimatch](https://github.com/isaacs/minimatch#features) here.  In RegEx, I think all of the above files would be isolated via `NAME.?(js)?`, right?

thanks :)

### LINKED ISSUE #78: Closest matching
A query endpoint to find the closest match would be extremely convenient (current use case is duckduckgo spice answers).

What this would involve is determining the library that matches a query as close as possible (e.g. `jwuery` may match `jquery` if `jwuery` is not a library). Another thing this should support is searching for plugins

```
/search?name=jquery carousel => jquery.carousel
/search?name=jquery-carousel => jquery.carousel
``` 

There should be an arbitrary threshold to cut off in accurate matches based on levenshtein scores. I'd say `Math.min(query.length / 2, 4)`

Imagining the endpoint would be

```
http://api.jsdelivr.com/v2/jsdelivr/find?name={lib}
```

I'm imagining this returning a single result

### LINKED ISSUE #86: Exact matching for alias path
Alias path should use exact path rather than minimatch path

As discussed in gitter this shouldn't really work, and instead try to use exact match

```
http://api.jsdelivr.com/v1/jsdelivr/libraries/jq*
```

### PR DESCRIPTION
**Pull request by megawac**
This is a WIP and implementation of what we've been discussing in emails, gitter and gh issues

Adds `/library` and changes `/libraries` routes (see #85 and gitter for descriptions)

Fixes #10; Fixes #78; Fixes #86; Depends on #81 

TODO: documentation

### CODE REVIEW

**Comment by megawac** [comment]
Think this is good to go, can I get some :eyes:

**Comment by jimaek** [comment]
I dont understand much but it looks to me :+1:

**Comment by megawac** [comment]
Want to run api on that branch play around with it locally to see if it
works as you'd expect?

**Comment by jimaek** [comment]
Actually I think in any case we need to create a beta app for the v2 api for general testing. 
@UnbounDev Can you take care of that?

**Comment by UnbounDev** [comment]
Np - though we may have to up the memory available on appfog  (not sure) - we should still merge the PR though, since everything's going to the v2 branch we don't have to worry about impacting production  (I'll build the test app off of that branch).

**Comment by megawac** [comment]
This isn't ready to go yet. Still broken for a couple cases related to the lokijs filtering (it's fickle)

**Comment by megawac** [comment]
Alright think its good to go

**Comment by tomByrer** [comment]
Maybe add tests?  Good to ensure future changes (eg when LokiJS adds better filtering) can be added seamlessly.  & communicate to non-pro JS programmers what is expected.

**Comment by megawac** [comment]
I started writing some unit tests with `frisby` last night (https://github.com/jsdelivr/api/commit/0cd5279d2bc10ec496c18a565bab662780c3ee67), but was having some issues. If someone wants to figure out how to get them working it'd be easier

**Pull request merged**
