### PR TITLE
Freeze

### PR DESCRIPTION
**Pull request by MartinKolarik**
Adds a copy of data from http://46.4.74.152:8000/data/ to this repo and removes the remote sync.

### CODE REVIEW

**Comment by jimaek** [comment]
```
2017-06-08T18:28:29.293Z info Node (version: v8.0.0) /home/bas/app_9eea3a15-c961-4e51-9dec-fc5640be57b4/serve.js started on 8080 ...
2017-06-08T20:28:29.551+02:002017-06-08T18:28:29.309Z info Running tasks: sync
2017-06-08T20:28:29.551+02:002017-06-08T18:28:29.312Z info Running task sync...
2017-06-08T20:28:29.551+02:002017-06-08T18:28:29.429Z info Starting to sync v1/bootstrap from source /home/bas/app_9eea3a15-c961-4e51-9dec-fc5640be57b4/data/v1/bootstrap.json
2017-06-08T20:28:29.551+02:002017-06-08T18:28:29.432Z info Files for sync of v1/bootstrap retrieved from source /home/bas/app_9eea3a15-c961-4e51-9dec-fc5640be57b4/data/v1/bootstrap.json
2017-06-08T20:28:29.551+02:002017-06-08T18:28:29.440Z info Successfully synced libraries for v1/bootstrap
2017-06-08T20:28:29.552+02:002017-06-08T18:28:29.441Z info Starting to sync v1/cdnjs from source /home/bas/app_9eea3a15-c961-4e51-9dec-fc5640be57b4/data/v1/cdnjs.json
2017-06-08T20:28:29.552+02:002017-06-08T18:28:29.442Z info Files for sync of v1/cdnjs retrieved from source /home/bas/app_9eea3a15-c961-4e51-9dec-fc5640be57b4/data/v1/cdnjs.json
2017-06-08T20:28:31.801+02:002017-06-08T18:28:31.376Z warning Error syncing library!
2017-06-08T20:28:31.801+02:00{ cause:
2017-06-08T20:28:31.801+02:00 { name: 'Error',
2017-06-08T20:28:31.801+02:00 message: 'ENOENT: no such file or directory, open \'/home/bas/app_9eea3a15-c961-4e51-9dec-fc5640be57b4/data/v1/cdnjs/jquery-scrollto/library.json\'',
2017-06-08T20:28:31.801+02:00 errno: -2,
2017-06-08T20:28:31.801+02:00 code: 'ENOENT',
2017-06-08T20:28:31.802+02:00 syscall: 'open',
2017-06-08T20:28:31.802+02:00 path: '/home/bas/app_9eea3a15-c961-4e51-9dec-fc5640be57b4/data/v1/cdnjs/jquery-scrollto/library.json',
2017-06-08T20:28:31.802+02:00 stack: [ 'Error: ENOENT: no such file or directory, open \'/home/bas/app_9eea3a15-c961-4e51-9dec-fc5640be57b4/data/v1/cdnjs/jquery-scrollto/library.json\'' ] },
2017-06-08T20:28:31.802+02:00 isOperational: true,
2017-06-08T20:28:31.802+02:00 errno: -2,
2017-06-08T20:28:31.802+02:00 code: 'ENOENT',
2017-06-08T20:28:31.802+02:00 syscall: 'open',
2017-06-08T20:28:31.802+02:00 path: '/home/bas/app_9eea3a15-c961-4e51-9dec-fc5640be57b4/data/v1/cdnjs/jquery-scrollto/library.json',
2017-06-08T20:28:31.802+02:00 time: '2017-06-08T18:28:31.378Z',
2017-06-08T20:28:31.802+02:00 level: 'warning' }
2017-06-08T20:28:34.216+02:00GET /v1/bootstrap/libraries/font-awesome/ 200 0.821 ms - 12359
2017-06-08T20:28:34.300+02:00Application start successful
2017-06-08T20:28:34.301+02:00No cron to setup
2017-06-08T20:28:34.301+02:00GET / 404 5.764 ms - 62
2017-06-08T20:28:34.301+02:00Created symlink /etc/systemd/system/multi-user.target.wants/zabbix-agentd.service → /usr/x86_64-pc-linux-gnu/lib/systemd/system/zabbix-agentd.service.
```

**Comment by MartinKolarik** [comment]
Hmm there are two different libraries, one called `jquery-scrollto` and another called `jquery-scrollTo`. One of them got lost on my machine since windows fs is case-insensitive.

**Comment by MartinKolarik** [comment]
Have you deleted http://46.4.74.152:8000/data/ already?

**Comment by jimaek** [comment]
I stopped the service for testing. Should be up now.

**Pull request merged**
