### PR TITLE
Feature/analytics

### LINKED ISSUE #62: Add analytics
I am now parsing our access logs and populating a mysql DB with the number of hits per project.

What is the best way to make this data public? Should we create a new endpoint e.g. `api.jsdelivr.com/v2/analytics/` or just a new field inside each project with the reporting data?

I guess api-sync can pull the data itself from the DB(and cache it), right? No need for me to write a proxy between the DB and the API, correct?
The data we have is: date, project, hits. 

@megawac @UnbounDev

### PR DESCRIPTION
**Pull request by UnbounDev**
- Add SQL knex client.
- Add `/v2/analytics/:library` endpoint.
- Includes WIP v2 docs.

Closes #62

### CODE REVIEW

**Comment by UnbounDev** [comment]
@jimaek this should be ready to go but you'll have to add `SQL_HOST` and `SQL_PASSWORD` environment variables to the appfog instance.

**Comment by jimaek** [comment]
Do you cache the analytics data on the API or you hit the DB every time?

**Comment by UnbounDev** [comment]
I hit the db

**Comment by jimaek** [comment]
Ok. Well it looks good to me. 
@megawac Any feedback? Is it good to go?

**Comment by jimaek** [comment]
Btw part of the analytics data is delayed by 2 days. Any ideas what we should do?
Simply show what we have or dont allow the user to get the data for the last 2 days at all?

**Comment by UnbounDev** [comment]
I'd say show what we have, and document the analytics limitations.

**Comment by pnommensen** [comment]
+1

We'd need to keep an eye on the usage and if necessary cache the results for some minutes. But otherwise this looks good :)

**Comment by megawac** [comment]
looks great

**Comment by jimaek** [comment]
Is this live on the v2 demo app?
http://jsdelivr-apiv2-test.aws.af.cm/v2/analytics/jquery

**Comment by jimaek** [comment]
ping @UnbounDev

**Comment by UnbounDev** [comment]
@jimaek it should be live, yes, but the test instance on appfog is dead and I haven't been able to get a successful deploy, even manually via the cli (appfog always seems to miss installing an npm dependency and the app won't start).

**Comment by jimaek** [comment]
The app works locally for you? Thats strange, appfog is unstable but not that unstable

**Pull request merged**
