### PR TITLE
Add optional `limit` query parameter

### PR DESCRIPTION
**Pull request by gavinhungry**
See issue #126.

The tests don't seem to run, but I wrote a test for this anyway. The test may need testing, as tests do. We should also consider a default limit - you don't need to return up to ~1000 results for every search.

### CODE REVIEW

**Comment by MartinKolarik** [comment]
@jimaek do you want to add this to v1 or v2? This PR goes to v1.

**Comment by jimaek** [comment]
v1 the actually live API

**Comment by MartinKolarik** [comment]
I know which is why I'm asking if you want to add it to the live version.

**Comment by jimaek** [comment]
Yes, thats what I meant. No point adding to v2 right now

**Pull request closed without merging**
